[package]
name = "tureng-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = { version = "2.6", default-features = false }
miniserde = "0.1"
termion = "2"
libc = "0.2"

[profile.release-pr]
inherits = "release"
lto = true
panic = "abort"
codegen-units = 1
strip = true
opt-level = 3
